<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_15 minutes</name>
   <tag></tag>
   <elementGuidId>41f513cc-0042-4f99-95a9-748f25d071df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-21940-option-15</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='select-21940-option-15']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a7553b7-5665-47ae-9bfc-f46d09447bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u1xbh6v5 c63nwm7</value>
      <webElementGuid>f44cb9a1-307e-41da-a916-aa9165dfd677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-21940-option-15</value>
      <webElementGuid>b07d2206-19b2-459c-88bf-e6d70c93a7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6770e663-8f39-40de-9c52-6912d21e7d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6054d926-8322-4e93-8932-f4211664d499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d2e48574-0e84-4c79-a984-94b3d59c5dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9e441d64-a404-4a18-888d-f5f78a8c1ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>15 minutes</value>
      <webElementGuid>dec5ff01-fe0d-417f-82bc-d667b4c5987f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-21940-option-15&quot;)</value>
      <webElementGuid>0a0f8042-32e7-4ba1-a883-1207d608da53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='select-21940-option-15']</value>
      <webElementGuid>3c8df876-680d-42c4-acd7-e420383790c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-21940-options']/button</value>
      <webElementGuid>e20aebfa-cb53-478d-ac04-03c3bcefa935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/following::button[1]</value>
      <webElementGuid>2876abda-c40f-435b-ac3e-081c9544fe0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India Standard Time'])[1]/following::button[1]</value>
      <webElementGuid>b39f5d4d-671e-4786-a009-6fa0ac189683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom'])[1]/preceding::button[4]</value>
      <webElementGuid>ca7a359f-3e7d-4381-8f15-81f6d61a9de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Host'])[1]/preceding::button[5]</value>
      <webElementGuid>0204b8f7-a8e9-4a01-8a5b-9d67794d7b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='15 minutes']/parent::*</value>
      <webElementGuid>da2ea59a-997a-4550-a6b3-0f91c769c4d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/button</value>
      <webElementGuid>be87e242-023b-4597-94ae-57c7fe66d264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'select-21940-option-15' and @type = 'button' and (text() = '15 minutes' or . = '15 minutes')]</value>
      <webElementGuid>04037d0f-540b-43d8-b05d-2e06366a08bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='select-5bbdb-option-15']</value>
      <webElementGuid>92d194e1-a92d-4180-9aea-3bf7643ea7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-5bbdb-options']/button</value>
      <webElementGuid>6d9a64d4-5de8-47f5-a8b0-2dc66c3d3427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'select-5bbdb-option-15' and @type = 'button' and (text() = '15 minutes' or . = '15 minutes')]</value>
      <webElementGuid>f4cdcc18-494a-4c03-a71b-ee7ba4c94c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='select-ffecb-option-15']</value>
      <webElementGuid>5fca669e-448a-49a8-b49a-53ca6eafec5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-ffecb-options']/button</value>
      <webElementGuid>22260e02-264c-4e94-ace4-80fac1b58be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'select-ffecb-option-15' and @type = 'button' and (text() = '15 minutes' or . = '15 minutes')]</value>
      <webElementGuid>ccf00819-d794-4232-b178-a6240b67c34f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
