<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_All day_eQPBrvcnu1AmZL8t3Sq1 zef5fzHcUh_6dd6de</name>
   <tag></tag>
   <elementGuidId>13bbc8c4-130e-47cc-9b7a-e65cee1c51b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[8]/div/div/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9a02db4-8797-4515-80a1-f2b20b83e9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-time-range</name>
      <type>Main</type>
      <value>9:15am - 9:30am</value>
      <webElementGuid>66713629-c331-4f28-b5cd-441a6b5651cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>has-votes</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>6339d004-7eb3-4022-910a-826a608a6095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eQPBrvcnu1AmZL8t3Sq1 zef5fzHcUh4hanNiAxYt</value>
      <webElementGuid>859e49ad-987f-4c1b-ad29-84d59cc25a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;Es8downQlxiASDyltHtn HhJ8keLZ1SBupKzmsP0V _C_TCiqAjdTOkIIzyy7N hzNtQT3DRnRbKEc8uEG2 _CT5fMYYPxxNEyDeQ0Jh&quot;]/div[@class=&quot;p1fv2xvi c148e1tk&quot;]/div[@class=&quot;sdqpodb&quot;]/div[@class=&quot;ik2zh9x&quot;]/div[@class=&quot;iKiHm2OV3O0V1m7iw913 ebannVwMa5zA_j5Oi67A&quot;]/div[@class=&quot;_ifRS_qvL8xEX9WQrdvA NksYKegVQcKqiqtmvYzj&quot;]/div[@class=&quot;Hrg5xQCWBsTBpkUAKhK9 CgsLs1LTluk0tXisF_Sp&quot;]/div[@class=&quot;zFy_IkFk1k0zVBr3jfnn pINn7II6lDQ3ZNXXpl5v&quot;]/div[@class=&quot;lGi7fUKEYQV_s461YY90 l6CTdFuKpyXrv8mQoRKX iazDNT_6bSOQgh1wdgYL&quot;]/div[@class=&quot;fc fc-media-screen fc-direction-ltr fc-theme-standard&quot;]/div[@class=&quot;fc-view-harness fc-view-harness-active&quot;]/div[@class=&quot;fc-timegrid fc-timeGridSevenDay-view fc-view&quot;]/table[@class=&quot;fc-scrollgrid  fc-scrollgrid-liquid&quot;]/tbody[1]/tr[@class=&quot;fc-scrollgrid-section fc-scrollgrid-section-body  fc-scrollgrid-section-liquid&quot;]/td[1]/div[@class=&quot;fc-scroller-harness fc-scroller-harness-liquid&quot;]/div[@class=&quot;fc-scroller fc-scroller-liquid-absolute&quot;]/div[@class=&quot;fc-timegrid-body&quot;]/div[@class=&quot;fc-timegrid-cols&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;fc-timegrid-col fc-day fc-day-sat fc-day-future&quot;]/div[@class=&quot;fc-timegrid-col-frame&quot;]/div[@class=&quot;fc-timegrid-col-bg&quot;]/div[@class=&quot;fc-timegrid-bg-harness&quot;]/div[@class=&quot;fc-bg-event fc-event fc-event-start fc-event-end fc-event-future&quot;]/div[@class=&quot;eQPBrvcnu1AmZL8t3Sq1 zef5fzHcUh4hanNiAxYt&quot;]</value>
      <webElementGuid>1488e94f-51e8-48ac-9a36-9c2b8232805b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/div/div[3]/div/div</value>
      <webElementGuid>99210fbd-702e-49e1-82bd-a1c6ec95588f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
