<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Next</name>
   <tag></tag>
   <elementGuidId>7416eed1-fbc1-4bbc-9133-6164c7c1566a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.b1hdxvdx.u1xbh6v5.b169yzjr.d1bkmipt.f1jbk2sk._Koqrbejxc8L_XgbntLw._lhfh_h2p_9O_nh5HfjO > div.t10keekh.t19egbtk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='All day'])[1]/following::div[175]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>531971c7-ce18-4be1-bb2f-13183c93f253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t10keekh t19egbtk</value>
      <webElementGuid>1c5e5b5b-455d-4671-afaa-6c08942bf597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>52920652-53ee-402a-8775-7d272490fa27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;Es8downQlxiASDyltHtn HhJ8keLZ1SBupKzmsP0V _C_TCiqAjdTOkIIzyy7N hzNtQT3DRnRbKEc8uEG2 _CT5fMYYPxxNEyDeQ0Jh&quot;]/div[@class=&quot;p1fv2xvi c148e1tk&quot;]/div[@class=&quot;sdqpodb&quot;]/div[@class=&quot;ik2zh9x&quot;]/div[@class=&quot;iKiHm2OV3O0V1m7iw913 ebannVwMa5zA_j5Oi67A&quot;]/div[@class=&quot;_ifRS_qvL8xEX9WQrdvA NksYKegVQcKqiqtmvYzj&quot;]/div[@class=&quot;AJZreTdZjsdw5uZiDZtP cnmyvV_Ltdw_BxjzzACc&quot;]/button[@class=&quot;b1hdxvdx u1xbh6v5 b169yzjr d1bkmipt f1jbk2sk _Koqrbejxc8L_XgbntLw _lhfh_h2p_9O_nh5HfjO&quot;]/div[@class=&quot;t10keekh t19egbtk&quot;]</value>
      <webElementGuid>f36d8866-9798-42dd-92a2-7df0e4f54328</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All day'])[1]/following::div[175]</value>
      <webElementGuid>973bfca0-652f-40ae-ac21-75612f67d8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear times'])[1]/following::div[179]</value>
      <webElementGuid>7e5adfac-170e-4fd8-aa15-e6b54c46a710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>cc577229-4832-48a0-b796-c9fa78b295d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button/div</value>
      <webElementGuid>40048071-5d52-4c9c-a484-41299c12b3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>b8817415-f174-4a3e-bdb1-beca71f9b799</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
