<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Edit</name>
   <tag></tag>
   <elementGuidId>ad4d0770-eb4c-46cd-945a-90f6fdf48b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.t1cc2kzd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/div/div/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4f4bc645-6607-4d58-96cc-d1139df936c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t1cc2kzd</value>
      <webElementGuid>cdce12ff-4940-475e-bc06-a6e3ae105513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>334f89f6-70f7-43b3-8f03-d7dec5b7198c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bQ_IvAJyMswLH8t9BfyH yohIaPQ8hKIYSUtsEb_W&quot;]/div[@class=&quot;KugZaZLca_qtYXtJk40b ZNeCdjc2mOlTaKHoVdtV&quot;]/main[@class=&quot;e5O3DgXvSgWPoACoTevm zq_pp2IBb5lpS8hhNM2e&quot;]/div[@class=&quot;flxs2ZLtEYubKgjI5tSt _Ntt9XmPLkf0xalYSzTt&quot;]/div[2]/div[@class=&quot;tDhRAV_Mr5iHcWo2ZWYm bCGU8a8O0jMHBmycapKf kjaazBgmXIEKBdlcsCID psF7fTI03fHMrXMb_j8_&quot;]/div[@class=&quot;Q1X31VHgypch04V9vC_T wGbE3zjEJO70bi87TmCI&quot;]/div[1]/div[@class=&quot;event-type-list js-list-region&quot;]/div[@class=&quot;event-type-group-list&quot;]/div[@class=&quot;event-type-group-list-item user-item&quot;]/div[2]/div[@class=&quot;event-type-card-list grid-3 ui-sortable&quot;]/div[@class=&quot;grid-3-cell&quot;]/div[@class=&quot;event-type-card taDbz08ZkE7XR3z4vSnW MSriZDRtutINWBehvmto&quot;]/div[@class=&quot;q2ovdrDio1O20z_RQrJk X3NIapMZh_JjFD04AwQ3&quot;]/div[@class=&quot;b17zwe44 b3sf25d _TLr4nMfZHeFDR3zh5YF NTDjgFdyBeUPtc7pEVdx c148e1tk&quot;]/div[@class=&quot;gtosasw&quot;]/button[@class=&quot;u1xbh6v5 b1b7gwr2&quot;]/div[@class=&quot;t1cc2kzd&quot;]</value>
      <webElementGuid>bbc46e4e-f919-431a-9c40-f12471f78126</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/div/div/button/div</value>
      <webElementGuid>6f8b8761-2781-4423-aff6-d2baccb182b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Event Type'])[1]/following::div[13]</value>
      <webElementGuid>e7d1a1e0-a345-4b26-8dff-9f793867c70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://calendly.com/rangisettijhansi'])[1]/following::div[16]</value>
      <webElementGuid>3dc3e403-19d2-43fe-8abb-5482bc79615d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Internal Note'])[1]/preceding::div[1]</value>
      <webElementGuid>7d8a23a0-9cff-4e8a-bce9-873f55e1b4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clone'])[1]/preceding::div[2]</value>
      <webElementGuid>ca82ed1b-ebd6-432d-8788-840fa8209574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>77b3f4ca-afe7-418c-b573-2bf5e1d86614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button/div</value>
      <webElementGuid>afac346c-49b3-4a44-9e7f-12248fce426a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>ae756fb3-3a71-41d2-8be3-3c43b0e00f81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
