<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Meeting name_name</name>
   <tag></tag>
   <elementGuidId>a722ac4e-ef04-4f3d-a23a-c5a24678d07d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oZsXQA8_9YacRjMFF5L1d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='oZsXQA8_9YacRjMFF5L1d']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16df8301-e379-4c00-b368-e72e3637671e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i1czu8b</value>
      <webElementGuid>3bc102d2-408d-4fd7-84dc-da24f0a998fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f1909da-2606-4da6-bb87-9d5344a984f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>55</value>
      <webElementGuid>99bbbfa0-d2c1-4a3c-ab86-e5e9e8e885c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>ad0b8773-d98e-433b-ae9b-55fe6ec17671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Introduction, group meeting, quick chat, etc.</value>
      <webElementGuid>b373dcfc-1ef2-4b8f-a18b-45f0406af77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oZsXQA8_9YacRjMFF5L1d</value>
      <webElementGuid>8cecf245-e9b0-4165-b0e6-51e3a2ac3861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>765a2b7d-ac6e-4b12-9d67-00b4c8f27fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d4e6ceaf-4741-4d90-b4e3-6526a32fd573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0a352303-0937-4aca-a9a0-1640174c8461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Meeting</value>
      <webElementGuid>8766801f-32cb-4fbb-a8f4-66fe416b276c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oZsXQA8_9YacRjMFF5L1d&quot;)</value>
      <webElementGuid>802f1805-cc71-4722-b323-60671b3521c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='oZsXQA8_9YacRjMFF5L1d']</value>
      <webElementGuid>7202b805-b38e-46e4-8ddd-c88b48be341e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='oneoff-creation-form']/div/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>0d993e39-1931-401e-9a7c-75e7d1466111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>26c4d6f4-3f69-407a-953f-df5f6a956637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'name' and @placeholder = 'Introduction, group meeting, quick chat, etc.' and @id = 'oZsXQA8_9YacRjMFF5L1d']</value>
      <webElementGuid>7116c638-4e14-4437-9052-5af192a50fd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
