<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_physicalAddress</name>
   <tag></tag>
   <elementGuidId>77edfc78-21b3-4d60-b366-8228d7aa0118</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_iZajVnO320lVZt0hCcEo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_iZajVnO320lVZt0hCcEo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df8ba440-d6db-4afb-863e-0b50a94a2e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i1czu8b</value>
      <webElementGuid>d424969e-99c1-403d-b18d-a54173592d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c40ce74-d510-42b1-a9df-47e3e64f39b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>e5513dba-0908-4936-8acb-8fcbbd5d8464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>physicalAddress</value>
      <webElementGuid>1ac0abc7-ddbc-45dd-9409-82d0847bd5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Specify physical address</value>
      <webElementGuid>13548729-63e8-4a2a-8af4-fdf77c28cb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_iZajVnO320lVZt0hCcEo</value>
      <webElementGuid>520f52eb-eb96-4782-866b-257d1bab009e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>044ec675-1dc0-46ac-a5fe-9ad437a464c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3e0ca558-64c1-4bb4-8875-c04dcb11ab41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>40e5d0bc-73e5-41e1-b4e3-4199841eb38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_iZajVnO320lVZt0hCcEo&quot;)</value>
      <webElementGuid>ea882aa6-96a5-468c-a69e-d87f3b41574a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_iZajVnO320lVZt0hCcEo']</value>
      <webElementGuid>8d72dea7-40c4-43c7-a766-cfec428aa185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='oneoff-creation-form']/div/div[2]/div[5]/div[2]/input</value>
      <webElementGuid>f534570f-db4c-42b6-bbc6-99328088497e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>0a05fed3-c858-4b22-a82a-28d0e7d155bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'physicalAddress' and @placeholder = 'Specify physical address' and @id = '_iZajVnO320lVZt0hCcEo']</value>
      <webElementGuid>f80f0fc2-aead-4a69-a5eb-cdcbcf169a70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
