<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Location Details_physicalDetails</name>
   <tag></tag>
   <elementGuidId>08de371b-74b6-4730-ad56-8a97db65e1e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cpla9lXHLVaTEIxg-ixjs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cpla9lXHLVaTEIxg-ixjs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e1ba18a-df30-4a61-9c6a-afecd62779da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i1czu8b</value>
      <webElementGuid>161c675c-9ee2-47ec-9cea-e098bc82e87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b099ee79-c4c4-4f0a-b595-23ef764aea85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>a200e22d-fffd-4fa9-a0d7-7cb96c09e99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>physicalDetails</value>
      <webElementGuid>e33db26a-e70e-466c-a3bb-f58bad1650e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Include additional information</value>
      <webElementGuid>59dfea27-8875-4213-b936-0fb9f8de0e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cpla9lXHLVaTEIxg-ixjs</value>
      <webElementGuid>21c8dbfe-19e3-4e23-8162-e6f8cb753ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>324c042b-8ef1-4950-9586-b8be27a3765d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cf7e9b14-79c4-4b30-8b13-39f04d8a40c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fa253612-6041-4b26-8e85-6829048236f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpla9lXHLVaTEIxg-ixjs&quot;)</value>
      <webElementGuid>0dd937af-9368-47c0-82c4-4b8399c575ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cpla9lXHLVaTEIxg-ixjs']</value>
      <webElementGuid>141b86ff-5cbc-4f2d-a674-f74b814f0bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='oneoff-creation-form']/div/div[2]/div[6]/div[2]/input</value>
      <webElementGuid>7cd7a10c-9bc7-49c6-9843-1e9f495c0923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>1bb18d63-6198-4dc7-8158-8e0bedbd0b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'physicalDetails' and @placeholder = 'Include additional information' and @id = 'cpla9lXHLVaTEIxg-ixjs']</value>
      <webElementGuid>59d711f6-c901-4405-881d-7da8d35bc407</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
