<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_New Event Type_A7tqJ6C1P8YpEgrEWrXi _X_8c9294</name>
   <tag></tag>
   <elementGuidId>c105d95f-2590-4bab-b981-77b9128102e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.A7tqJ6C1P8YpEgrEWrXi._XbQPUKWf22bA3jUPkNZ.ilgst7j.i1vl0pa6.n1qn271q</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f9d36297-478b-4f6b-a627-6c83a7455b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>A7tqJ6C1P8YpEgrEWrXi _XbQPUKWf22bA3jUPkNZ ilgst7j i1vl0pa6 n1qn271q</value>
      <webElementGuid>7fc7ffb1-136a-407f-9a19-37a8e970eb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bQ_IvAJyMswLH8t9BfyH yohIaPQ8hKIYSUtsEb_W&quot;]/div[@class=&quot;KugZaZLca_qtYXtJk40b ZNeCdjc2mOlTaKHoVdtV&quot;]/main[@class=&quot;e5O3DgXvSgWPoACoTevm zq_pp2IBb5lpS8hhNM2e&quot;]/div[@class=&quot;flxs2ZLtEYubKgjI5tSt _Ntt9XmPLkf0xalYSzTt&quot;]/div[2]/div[@class=&quot;tDhRAV_Mr5iHcWo2ZWYm bCGU8a8O0jMHBmycapKf kjaazBgmXIEKBdlcsCID psF7fTI03fHMrXMb_j8_&quot;]/div[@class=&quot;Q1X31VHgypch04V9vC_T wGbE3zjEJO70bi87TmCI&quot;]/div[1]/div[@class=&quot;event-type-list js-list-region&quot;]/div[@class=&quot;event-type-group-list&quot;]/div[@class=&quot;event-type-group-list-item user-item&quot;]/div[2]/div[@class=&quot;event-type-card-list grid-3 ui-sortable&quot;]/div[@class=&quot;grid-3-cell&quot;]/div[@class=&quot;event-type-card taDbz08ZkE7XR3z4vSnW MSriZDRtutINWBehvmto&quot;]/div[@class=&quot;q2ovdrDio1O20z_RQrJk X3NIapMZh_JjFD04AwQ3&quot;]/button[@class=&quot;b1hdxvdx u1xbh6v5 b3g11s8 Oq2YrD4C9wTAnhviKPh1 YiN2yIXsJlaCXNhdqJRX&quot;]/span[@class=&quot;A7tqJ6C1P8YpEgrEWrXi _XbQPUKWf22bA3jUPkNZ ilgst7j i1vl0pa6 n1qn271q&quot;]</value>
      <webElementGuid>293faf80-b604-4435-9148-3674652e4547</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div/div[3]/button/span[2]</value>
      <webElementGuid>8583e2e4-f2c5-49a4-a514-ba6b98c61085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span[2]</value>
      <webElementGuid>b73af842-be8f-48e6-aa40-21ee70ed6c32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
