<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_1_2</name>
   <tag></tag>
   <elementGuidId>282752a6-67c9-4338-8e51-c601c2c9e661</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.icj9ovg > span.b1hdxvdx.b1wd19y1.s1p6ipfe > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>de4ff77c-515d-446b-9721-14f0f1773259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 20 20</value>
      <webElementGuid>de087f15-ce36-401e-9fbd-50ec11a0c276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>6bd9cb4f-4e29-4666-a86d-954029d1001d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>e223a591-9ea3-43cb-92d0-5b3ea776d52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>23f2d09c-61de-4805-b890-1d36bba593f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;Es8downQlxiASDyltHtn HhJ8keLZ1SBupKzmsP0V _C_TCiqAjdTOkIIzyy7N hzNtQT3DRnRbKEc8uEG2 _CT5fMYYPxxNEyDeQ0Jh&quot;]/div[@class=&quot;p1fv2xvi c148e1tk&quot;]/div[@class=&quot;sdqpodb&quot;]/div[@class=&quot;ik2zh9x&quot;]/div[@class=&quot;iKiHm2OV3O0V1m7iw913 ebannVwMa5zA_j5Oi67A&quot;]/div[@class=&quot;_ifRS_qvL8xEX9WQrdvA NksYKegVQcKqiqtmvYzj&quot;]/div[@class=&quot;Hrg5xQCWBsTBpkUAKhK9 CgsLs1LTluk0tXisF_Sp&quot;]/div[@class=&quot;nDnwXHqvucJNiZ8VtmHU nguKnZQE9OTtZSoaYHbo&quot;]/div[@class=&quot;SCaRNJDV_jGW8lNC4NAq EvSIa42SuGvqwVe_hOTP&quot;]/div[1]/div[@class=&quot;b1hdxvdx s13brrra&quot;]/div[@class=&quot;u1xbh6v5 cuma89m&quot;]/div[@class=&quot;icj9ovg&quot;]/span[@class=&quot;b1hdxvdx b1wd19y1 s1p6ipfe&quot;]/svg[1]</value>
      <webElementGuid>af69d7e0-18ff-4ed6-8d2c-2f451a5f41a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>26b68705-268a-4eb5-8ff0-eb279a41e98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India Standard Time'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>e9f2c0b9-f8fb-4b2a-b2a4-4d80e1b4c75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Host'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>b18ef4a0-00f6-40fd-81f6-2e6e4608e3df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R'])[3]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>76cc79a2-845b-49cc-9f20-a4b8eecae4ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
