<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Continue</name>
   <tag></tag>
   <elementGuidId>68ccc5e7-a2f6-4253-b4e0-018794b0c90d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.t10keekh.t19egbtk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/form/div[2]/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a16f6861-c917-4058-8fea-77031e52b895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t10keekh t19egbtk</value>
      <webElementGuid>e4cfbf3b-e2ab-4014-8ca1-75b48dcd67b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>0b506dd5-397b-431b-8260-722ad59f8d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_6HnHU6AiYor25HH1wNE bKlGR_jxbF6eow3MDCDS&quot;]/div[@class=&quot;_CzkeYAjZBfYGb9CbJfC _hSfXX3QDc9IuHvpAOsi s9oqwmp&quot;]/form[1]/div[@class=&quot;q3yDurEaqsOY_FKGdSqg Linll2VjcD_H0iXN_2gd&quot;]/button[@class=&quot;b1hdxvdx u1xbh6v5 b169yzjr d1bkmipt f1jbk2sk&quot;]/div[@class=&quot;t10keekh t19egbtk&quot;]</value>
      <webElementGuid>2d397dd7-b652-4d73-8141-b83595406856</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[2]/button/div</value>
      <webElementGuid>8432bff7-b75e-4241-8530-fd860d1a0ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your password.'])[1]/following::div[3]</value>
      <webElementGuid>489d9378-0f7c-4137-8cb1-9866dcd4ac90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(This is not me.)'])[1]/following::div[6]</value>
      <webElementGuid>2684b2b1-b002-48d5-81f0-cd7e04c9bf69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='send me a recovery email'])[1]/preceding::div[1]</value>
      <webElementGuid>cf977d56-fbc6-4c91-ae4c-4827ea59901a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>ad36fbac-3153-4523-9f23-59adf32b02bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button/div</value>
      <webElementGuid>dcf65035-f8dc-461d-9859-5331b9fabcb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>cbb317dc-c74b-4876-b03f-cd783c89d056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div/button/div</value>
      <webElementGuid>bf309faf-175d-4875-ad2d-c0cbd9a8c9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your email to get started.'])[1]/following::div[2]</value>
      <webElementGuid>56b21cfa-7c7e-4c9d-a350-139a33a790ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log into your Calendly account'])[1]/following::div[7]</value>
      <webElementGuid>ba945143-0248-4b39-8449-b3b056e6daa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/preceding::div[2]</value>
      <webElementGuid>9d58a1b9-2695-4641-a228-3197ed6a442f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in with Google'])[1]/preceding::div[5]</value>
      <webElementGuid>549d4066-1876-4090-8792-42818b948974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>5fb33d61-d1e9-4b14-839e-4eab27d1e993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
