<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your password_password</name>
   <tag></tag>
   <elementGuidId>e74d7e3e-278d-41fa-b4cc-e1f894522a53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#v5cFPwiyrhVZmf-hDRt0L</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f0c3dbd-5431-405e-afa4-e42ac49586ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i1czu8b</value>
      <webElementGuid>b27a7e67-9eab-41be-a3fb-cd45fc855765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>61e71f97-113b-4d5d-b320-ad287b9e69db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>3efe7709-6c1b-4151-8e93-d86db9bc126b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>aa5ec5cb-aeb7-4645-bf0f-249f23e8b509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d0178d77-31f2-4cc5-a477-11641907b7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>v5cFPwiyrhVZmf-hDRt0L</value>
      <webElementGuid>ef02e9b1-5a2d-4999-a139-b49eaa2895f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>49af5e50-4e2b-471e-bebe-6472ee97b4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>8f3fdb60-0fe1-4f9e-8ed5-2b083db80426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bc2c7d7d-bac7-4fd4-9b68-3a0906bb858b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>J</value>
      <webElementGuid>08061ee2-c123-4bdb-ad33-969cf7e7ba88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;v5cFPwiyrhVZmf-hDRt0L&quot;)</value>
      <webElementGuid>9647c5cd-a0b6-411b-986e-0e2a18b54897</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='v5cFPwiyrhVZmf-hDRt0L']</value>
      <webElementGuid>bc04f656-eeba-477b-99d1-d837eef35fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div/div[2]/input</value>
      <webElementGuid>8c800937-c476-4cb2-b165-d2197eaf7e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6cf8cff6-5b5f-4cb0-824a-31b50093a087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @placeholder = 'password' and @id = 'v5cFPwiyrhVZmf-hDRt0L']</value>
      <webElementGuid>80e9bb66-0fa1-4b91-9a52-e0e75a3cda65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cGTmemn3r3X4Foi1cYgGR']</value>
      <webElementGuid>d65818fa-206b-4fd7-b032-c1890910849e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @placeholder = 'password' and @id = 'cGTmemn3r3X4Foi1cYgGR']</value>
      <webElementGuid>50483166-43b6-46e9-8714-b4087e8a8101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SXiMADnHH08FH5vUPrDw_']</value>
      <webElementGuid>3db8227d-6673-4dd1-9dba-47df549c3afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @placeholder = 'password' and @id = 'SXiMADnHH08FH5vUPrDw_']</value>
      <webElementGuid>7c20dfd5-cd2a-449e-96f9-a1cade3d449d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pcm9-nFujk27ZYDq4UCMi']</value>
      <webElementGuid>aa8f443f-c91f-4a0b-880b-26c38d3aabc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @placeholder = 'password' and @id = 'pcm9-nFujk27ZYDq4UCMi']</value>
      <webElementGuid>519fe23c-6402-49e8-a462-71f7d5a999a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tHiyYQtpHPNuI8iREcNSA']</value>
      <webElementGuid>257525b6-2081-46a6-b49b-e34b30a2d0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @placeholder = 'password' and @id = 'tHiyYQtpHPNuI8iREcNSA']</value>
      <webElementGuid>c7a3b889-4377-4b6c-854b-05514e196e1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
