<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your email to get started_email</name>
   <tag></tag>
   <elementGuidId>978d4cba-54cc-4dfe-8662-432b7b2a1bd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ITvcSVWwM88hepcuiSCKF</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ITvcSVWwM88hepcuiSCKF']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02f854e3-0557-4eb9-894a-f4378b9fc2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i1czu8b</value>
      <webElementGuid>8c987417-e9c5-4713-95dc-1cfe560714c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>22876863-95d9-49ae-8b3a-84381b9dfd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>e808a22f-167b-4705-b799-5dd7cac52fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>56bbfaf5-ca63-4f28-9134-4229845fa940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>email address</value>
      <webElementGuid>7eae8954-ad05-4895-84ed-58e6816a6923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ITvcSVWwM88hepcuiSCKF</value>
      <webElementGuid>919ab032-ec25-406d-9cc6-7a09ca5fae75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3bb6a271-ee87-4772-83ac-4ad2d745d4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b72f8dcb-e37d-48eb-a559-35edaeca3d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d4abf76d-8d95-40e3-ab64-99798c0cdc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>r</value>
      <webElementGuid>bdcaad6a-ba01-47bf-9986-0acc36ea9dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ITvcSVWwM88hepcuiSCKF&quot;)</value>
      <webElementGuid>2618e7be-b84f-41b4-97bc-508fe87dbacc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ITvcSVWwM88hepcuiSCKF']</value>
      <webElementGuid>1a396109-2760-4832-a8e6-726d523990b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div/div/div/div[2]/input</value>
      <webElementGuid>662a8888-22a7-4dec-864d-20755a424e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c74f57a0-3fd1-443b-9012-fb5b30ba8b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @placeholder = 'email address' and @id = 'ITvcSVWwM88hepcuiSCKF']</value>
      <webElementGuid>ac9047f3-89e0-4e90-b615-ff16cdf4ae7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
