<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_What event is this30 Minute Meeting, No_aa4484</name>
   <tag></tag>
   <elementGuidId>f7eb3a16-f399-493c-95e9-507a54f82bcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.EOucS6QiITe8Rc3WGfSf.UsGUq4qbHOvAgPWQfxOB._DDc93pE0ebP6gec4iA_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main/div[2]/div[2]/div/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>edf64ef8-1c77-48ba-824b-57d9b8fff11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component</name>
      <type>Main</type>
      <value>section-header</value>
      <webElementGuid>8a15aef9-1b81-4b22-9ecb-fced4cc46230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EOucS6QiITe8Rc3WGfSf UsGUq4qbHOvAgPWQfxOB _DDc93pE0ebP6gec4iA_</value>
      <webElementGuid>d2a0a96b-827e-4305-ad84-3171002193ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What event is this?30 Minute Meeting, No location given</value>
      <webElementGuid>f4236f1c-3880-4985-8886-bcfba74041c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bQ_IvAJyMswLH8t9BfyH yohIaPQ8hKIYSUtsEb_W&quot;]/div[@class=&quot;KugZaZLca_qtYXtJk40b ZNeCdjc2mOlTaKHoVdtV&quot;]/main[@class=&quot;e5O3DgXvSgWPoACoTevm zq_pp2IBb5lpS8hhNM2e&quot;]/div[@class=&quot;eEb0Fmxt0mOrtpg3TFkq OCgQR4Sw7btifGdRSQvA&quot;]/div[@class=&quot;SX9fd9uS_mH7_DkBTsVD K5RosUM0yhlvRYO2eqDb&quot;]/div[@class=&quot;KzyrablSD6JlE9Kp_Jly K_WfMNDmI__bnkprluz1 _0HNzY4Ubb38UsAvw6c4&quot;]/button[@class=&quot;u1xbh6v5 S1Ux16_NLOefrMjLsfrY dS3c4fTZibEoaN53FLgQ&quot;]/div[@class=&quot;EOucS6QiITe8Rc3WGfSf UsGUq4qbHOvAgPWQfxOB _DDc93pE0ebP6gec4iA_&quot;]</value>
      <webElementGuid>6e03e086-d576-45d6-984c-d799c43dcc31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div[2]/div[2]/div/button/div</value>
      <webElementGuid>eae848f2-1e61-467e-ada1-91ef55b83687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::div[3]</value>
      <webElementGuid>392422d5-29f3-49ac-8297-ca9337bd5212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View live page'])[1]/following::div[5]</value>
      <webElementGuid>64466c8b-8c3a-4cdb-841b-8f2bbc098ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button/div</value>
      <webElementGuid>9e3a638a-51a1-4927-91e0-92fe46130890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'What event is this?30 Minute Meeting, No location given' or . = 'What event is this?30 Minute Meeting, No location given')]</value>
      <webElementGuid>e5bf9b8b-50a3-4687-962b-0ad89bfbafc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
